//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Project_2_Commiter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Software_Project_2_Commiter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] avatar {
            get {
                object obj = ResourceManager.GetObject("avatar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bunifu_UI_v1_52 {
            get {
                object obj = ResourceManager.GetObject("Bunifu_UI_v1_52", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Guna_UI2 {
            get {
                object obj = ResourceManager.GetObject("Guna_UI2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Counter from &quot;./Counter&quot;;
        ///const RESEARCH = ({ dark }) =&gt; 
        ///{
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;RESEARCH&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_about&quot;&gt;
        ///        &lt;div className=&quot;container&quot;&gt;
        ///          &lt;div className=&quot;wrapper&quot;&gt;
        ///            &lt;div className=&quot;left&quot;&gt;
        ///              &lt;div className=&quot;image&quot;&gt;
        ///                &lt;div className=&quot;numbers year&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div className=&quot;numbers project&quot;&gt;
        ///                &lt;/div&gt;
        ///              &lt;/div&gt;
        ///            &lt;/div&gt;
        ///            &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mahbub_RESEARCH {
            get {
                return ResourceManager.GetString("Mahbub_RESEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Counter from &quot;./Counter&quot;;
        ///const RESEARCH = ({ dark }) =&gt; 
        ///{
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;RESEARCH&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_about&quot;&gt;
        ///        &lt;div className=&quot;container&quot;&gt;
        ///          &lt;div className=&quot;wrapper&quot;&gt;
        ///            &lt;div className=&quot;left&quot;&gt;
        ///              &lt;div className=&quot;image&quot;&gt;
        ///                &lt;div className=&quot;numbers year&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div className=&quot;numbers project&quot;&gt;
        ///                &lt;/div&gt;
        ///              &lt;/div&gt;
        ///            &lt;/div&gt;
        ///            &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Morsalim_RESEARCH {
            get {
                return ResourceManager.GetString("Morsalim_RESEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { useEffect, useState } from &quot;react&quot;;
        ///import { fatchData } from &quot;../utilits&quot;;
        ///const Contact = () =&gt; {
        ///  const [data, setData] = useState({});
        ///  useEffect(async () =&gt; {
        ///    setData(await fatchData(&quot;/static/info.json&quot;));
        ///  }, []);
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;contact&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_contact&quot;&gt;
        ///        &lt;div className=&quot;container&quot;&gt;
        ///          &lt;div className=&quot;dizme_tm_main_title&quot; data-align=&quot;center&quot;&gt;
        ///            &lt;span&gt;Contact&lt;/span&gt;
        ///          &lt;/div&gt;
        ///          &lt;div cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mredul_Contact {
            get {
                return ResourceManager.GetString("Mredul_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const Header = ({ logo }) =&gt; {
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_header&quot;&gt;
        ///      &lt;div className=&quot;container&quot;&gt;
        ///        &lt;div className=&quot;inner&quot;&gt;
        ///          &lt;div className=&quot;logo&quot;&gt;
        ///            &lt;a href=&quot;#&quot;&gt;
        ///            &lt;/a&gt;
        ///          &lt;/div&gt;
        ///          &lt;div className=&quot;menu&quot;&gt;
        ///            &lt;ul className=&quot;anchor_nav&quot;&gt;
        ///              &lt;li className=&quot;current&quot;&gt;
        ///                &lt;a href=&quot;#home&quot;&gt;Home&lt;/a&gt;
        ///              &lt;/li&gt;
        ///              &lt;li&gt;
        ///                &lt;a href=&quot;#BIO&quot;&gt;BIO&lt;/a&gt;
        ///              &lt;/li&gt;
        ///              &lt;li&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Palki_Header {
            get {
                return ResourceManager.GetString("Palki_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import parse from &quot;html-react-parser&quot;;
        ///import { useEffect, useState } from &quot;react&quot;;
        ///import { fatchData } from &quot;../utilits&quot;;
        ///
        ///const Home = ({ dark }) =&gt; {
        ///  const [data, setData] = useState({});
        ///  useEffect(async () =&gt; {
        ///    setData(await fatchData(&quot;/static/info.json&quot;));
        ///  }, []);
        ///
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;home&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_hero&quot;&gt;
        ///        &lt;div
        ///          className=&quot;background&quot;
        ///          data-img-url={`img/slider/${dark ? 2 : 1}.jpg`}
        ///          // style={{ backgr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Palki_Home {
            get {
                return ResourceManager.GetString("Palki_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Counter from &quot;./Counter&quot;;
        ///const BIO = ({ dark }) =&gt; {
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;BIO&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_about&quot;&gt;
        ///        &lt;div className=&quot;container&quot;&gt;
        ///          &lt;div className=&quot;wrapper&quot;&gt;
        ///            &lt;div className=&quot;left&quot;&gt;
        ///              &lt;div className=&quot;image&quot;&gt;
        ///                &lt;div className=&quot;numbers year&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div className=&quot;numbers project&quot;&gt;
        ///                &lt;/div&gt;
        ///              &lt;/div&gt;
        ///            &lt;/div&gt;
        ///            &lt;div classNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rayhan_BIO {
            get {
                return ResourceManager.GetString("Rayhan_BIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Head from &quot;next/head&quot;;
        ///import BIO from &quot;../src/components/BIO&quot;;
        ///import RESEARCH from &quot;../src/components/RESEARCH&quot;;
        ///import PUBLICATIONS from &quot;../src/components/PUBLICATIONS&quot;;
        ///import TEACHING from &quot;../src/components/TEACHING&quot;;
        ///import Contact from &quot;../src/components/Contact&quot;;
        ///import Home from &quot;../src/components/Home&quot;;
        ///import Layout from &quot;../src/layout/Layout&quot;;
        ///
        ///const Index = () =&gt; {
        ///  return (
        ///    &lt;Layout&gt;
        ///      &lt;Head&gt;
        ///        &lt;title&gt;Stanford | PROFILES&lt;/title&gt;
        ///      &lt;/Head&gt;
        ///      &lt;Home /&gt;
        ///      {/* HER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rayhan_index {
            get {
                return ResourceManager.GetString("Rayhan_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Counter from &quot;./Counter&quot;;
        ///const PUBLICATIONS = ({ dark }) =&gt; {
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;PUBLICATIONS&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_about&quot;&gt;
        ///        &lt;div className=&quot;container&quot;&gt;
        ///          &lt;div className=&quot;wrapper&quot;&gt;
        ///            &lt;div className=&quot;left&quot;&gt;
        ///              &lt;div className=&quot;image&quot;&gt;
        ///                &lt;div className=&quot;numbers year&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div className=&quot;numbers project&quot;&gt;
        ///                &lt;/div&gt;
        ///              &lt;/div&gt;
        ///            &lt;/div&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sadman_PUBLICATIONS {
            get {
                return ResourceManager.GetString("Sadman_PUBLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Counter from &quot;./Counter&quot;;
        ///const BIO = ({ dark }) =&gt; {
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;BIO&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_about&quot;&gt;
        ///        &lt;div className=&quot;container&quot;&gt;
        ///          &lt;div className=&quot;wrapper&quot;&gt;
        ///            &lt;div className=&quot;left&quot;&gt;
        ///              &lt;div className=&quot;image&quot;&gt;
        ///                &lt;div className=&quot;numbers year&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div className=&quot;numbers project&quot;&gt;
        ///                &lt;/div&gt;
        ///              &lt;/div&gt;
        ///            &lt;/div&gt;
        ///            &lt;div classNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shafin_BIO {
            get {
                return ResourceManager.GetString("Shafin_BIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Head from &quot;next/head&quot;;
        ///import { useEffect } from &quot;react&quot;;
        ///import BIO from &quot;../src/components/BIO&quot;;
        ///import RESEARCH from &quot;../src/components/RESEARCH &amp; SCHOLARSHIP&quot;;
        ///import PUBLICATIONS from &quot;../src/components/PUBLICATIONS&quot;;
        ///import TEACHING from &quot;../src/components/TEACHING&quot;;
        ///import Contact from &quot;../src/components/Contact&quot;;
        ///import Home from &quot;../src/components/Home&quot;;
        ///import Layout from &quot;../src/layout/Layout&quot;;
        ///
        ///const Portfolio = dynamic(() =&gt; import(&quot;../src/components/Portfolio&quot;), {
        ///  ssr: false,
        ///});
        ///
        ///con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shafin_index_dark {
            get {
                return ResourceManager.GetString("Shafin_index_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shafin_info {
            get {
                object obj = ResourceManager.GetObject("Shafin_info", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import { useEffect, useState } from &quot;react&quot;;
        ///import { fatchData } from &quot;../utilits&quot;;
        ///const Contact = () =&gt; {
        ///  const [data, setData] = useState({});
        ///  useEffect(async () =&gt; {
        ///    setData(await fatchData(&quot;/static/info.json&quot;));
        ///  }, []);
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;contact&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_contact&quot;&gt;
        ///        &lt;div className=&quot;container&quot;&gt;
        ///          &lt;div className=&quot;dizme_tm_main_title&quot; data-align=&quot;center&quot;&gt;
        ///            &lt;span&gt;Contact&lt;/span&gt;
        ///          &lt;/div&gt;
        ///          &lt;div cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shojib_Contact {
            get {
                return ResourceManager.GetString("Shojib_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Counter from &quot;./Counter&quot;;
        ///const TEACHING = ({ dark }) =&gt; {
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;TEACHING&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_about&quot;&gt;
        ///        &lt;div className=&quot;container&quot;&gt;
        ///          &lt;div className=&quot;wrapper&quot;&gt;
        ///            &lt;div className=&quot;left&quot;&gt;
        ///              &lt;div className=&quot;image&quot;&gt;
        ///                &lt;div className=&quot;numbers year&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div className=&quot;numbers project&quot;&gt;
        ///                &lt;/div&gt;
        ///              &lt;/div&gt;
        ///            &lt;/div&gt;
        ///            &lt;di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Toha_TEACHING {
            get {
                return ResourceManager.GetString("Toha_TEACHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import Counter from &quot;./Counter&quot;;
        ///const TEACHING = ({ dark }) =&gt; {
        ///  return (
        ///    &lt;div className=&quot;dizme_tm_section&quot; id=&quot;TEACHING&quot;&gt;
        ///      &lt;div className=&quot;dizme_tm_about&quot;&gt;
        ///        &lt;div className=&quot;container&quot;&gt;
        ///          &lt;div className=&quot;wrapper&quot;&gt;
        ///            &lt;div className=&quot;left&quot;&gt;
        ///              &lt;div className=&quot;image&quot;&gt;
        ///                &lt;div className=&quot;numbers year&quot;&gt;
        ///                &lt;/div&gt;
        ///                &lt;div className=&quot;numbers project&quot;&gt;
        ///                &lt;/div&gt;
        ///              &lt;/div&gt;
        ///            &lt;/div&gt;
        ///            &lt;di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Towshib_TEACHING {
            get {
                return ResourceManager.GetString("Towshib_TEACHING", resourceCulture);
            }
        }
    }
}
